[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = /dev/tty.usbserial-AD025JRF

board_build.filesystem = littlefs

lib_deps =
  tzapu/WiFiManager@^2.0.17
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0
