[common]
lib_deps =
  tzapu/WiFiManager@^2.0.17
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = /dev/tty.usbserial-AD025JRF
board_build.filesystem = littlefs
lib_deps = ${common.lib_deps}

[env:nodemcuv2-ota]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = hood-control.local
board_build.filesystem = littlefs
lib_deps = ${common.lib_deps}
